### ISSUE TITLE
Tạo trang error thân thiện 

### ISSUE THREAD

**Issue by AnTTSE61258** [AnTTSE61258/cdsb#10]
<img width="1203" alt="screen shot 2016-02-24 at 1 14 54 pm" src="https://cloud.githubusercontent.com/assets/9337622/13277097/b183b884-daf8-11e5-8c32-877faeb729ce.png">

**Comment by AnTTSE61258** [comment]
Trang hiện tại như cứt luôn 

Ảnh có thể dùng được:

[https://scontent-sit4-1.xx.fbcdn.net/hphotos-xpt1/t31.0-8/s960x960/12697139_1086416858068998_5831675374389073331_o.png](url)

**Comment by Nadreasky** [comment]
này xong chưa, bữa thí mần xong gòi mà, xong thì đóng lại đi nha :3
