### ISSUE TITLE
[Bug] Khi đọc bằng mobile thì phần thừa 2 bên quá nhìu 

### ISSUE THREAD

**Issue by AnTTSE61258** [AnTTSE61258/cdsb#19]
<img width="258" alt="screen shot 2016-03-02 at 1 43 18 pm" src="https://cloud.githubusercontent.com/assets/9337622/13452686/d0562592-e07c-11e5-9732-341d811de8e3.png">

**Comment by Nadreasky** [comment]
commit lộn

**Comment by Nadreasky** [comment]
lỗi là do cái <div id ="site-container" có padding 2 bên là 20, nhưng hiện tai chưa biết nó nằm chỗ nào để sửa lại :|
![capture](https://cloud.githubusercontent.com/assets/15942198/13459569/2d94ee94-e0a7-11e5-9c93-7b1fd9a75eef.PNG)

**Comment by Nadreasky** [comment]
đã biết chỗ nào, nhưng nếu xóa padding thì fần logo fía trên bị che
![capture](https://cloud.githubusercontent.com/assets/15942198/13459806/c4246366-e0a8-11e5-9f49-5bbc4ebc8afa.PNG)
