### ISSUE TITLE
Fix loi bai viet moi bi nam duoi

### ISSUE THREAD

**Issue by AnTTSE61258** [AnTTSE61258/cdsb#9]

**Comment by AnTTSE61258** [comment]
commit 6ed2670327b86ca16248ce6570992cb1b9809828

**Comment by Nadreasky** [comment]
hình như lỗi này vẫn còn, bài post mới ko thấy hiện lên trang chủ
[http://capdoishowbiz.com/post/tran-thanh-tuyen-bo-su-that-ve-tinh-cam-voi-hari-won](url)
